### ISSUE TITLE
typing M as a command crashes the app

### ISSUE THREAD

**Issue by TheBotlyNoob** [staetyk/NxNxN-Cubes#3]
I'm unsure as to why this is. Here's a traceback:
```asm
M
Traceback (most recent call last):
  File "/home/jj/github/NxNxN-Cubes/main.py", line 79, in <module>
    exec(txt)
  File "<string>", line 1, in <module>
  File "/home/jj/github/NxNxN-Cubes/NxN.py", line 94, in <lambda>
    M = M1 = lambda l = n // 2: slice(turnL, l, False)
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jj/github/NxNxN-Cubes/NxN.py", line 75, in slice
    raise ValueError()
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jj/github/NxNxN-Cubes/main.py", line 84, in <module>
    error(e)
  File "/home/jj/github/NxNxN-Cubes/main.py", line 13, in error
    print (f"\u001b[2J\u001b[H\u001b[m\u001b[1;38;2;255;0;0m{str(x.args[0]).strip('(').strip(')')}\u001b[m", sep = "", end = "")
                                                                 ~~~~~~^^^
IndexError: tuple index out of range
```
Looks really cool, FYI.

**Comment by staetyk** [comment]
M, S, and E are all only for 3x3x3s, and don't have generalized forms, so I decided to remove them from the program. In order to implement them, try inputting something like this:

`M = R L' X`

Or maybe this:

`M = 2L`

Etc.
